# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-22 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sacms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('personnel', models.CharField(max_length=1000)),
                ('directions', models.CharField(max_length=1000)),
                ('projects', models.CharField(max_length=1000)),
                ('papers', models.TextField()),
            ],
        ),
    ]
