# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-24 03:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sacms', '0002_researchgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchgroup',
            name='leader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='researchgroup',
            name='personnel',
        ),
        migrations.AddField(
            model_name='researchgroup',
            name='personnel',
            field=models.ManyToManyField(blank=True, related_name='_researchgroup_personnel_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
