# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-26 08:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sacms', '0003_meeting'),
        ('sacms', '0003_auto_20161124_0305'),
    ]

    operations = [
    ]
