# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-26 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sacms', '0004_merge_20161126_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='myFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('team', models.CharField(max_length=1000)),
                ('country', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
    ]
